"""Generate grid_coords_full_field.yaml: the fixed implant's electrode grid.

This models ONE realistic device used by every blindness type (the electrodes do
not move with the diagnosis). It is cortical-magnification realistic -- most
electrodes sit on foveal V1 (dense centre), with a sparser tail extending into
the near periphery so the same device can also serve peripheral loss (glaucoma).

It is generated by sampling V1 cortex uniformly over the band that projects to
0..~26 deg of visual field and keeping the electrodes whose projection lands in
range. Uniform-in-cortex sampling automatically yields cortical-magnification
density in the visual field (dense fovea, sparse periphery).

The C++ side shows the device's full +/-DEVICE_HALF_FOV_DEG field to scale, so
keep DEVICE_HALF_FOV_DEG matched to C++ kDeviceFieldTan == tan(DEVICE_HALF_FOV).

Run (project dir, native_sdk env):  python generate_device_coords.py
"""

import os
import numpy as np

from dynaphos.utils import (load_params, load_coordinates_from_yaml, Map,
                            cartesian_to_complex, complex_to_polar)
from dynaphos.cortex_models import (get_mapping_from_cortex_to_visual_field,
                                    get_visual_field_coordinates_from_cortex_full)

# ---- knobs -----------------------------------------------------------------
SEED = 7
DEVICE_HALF_FOV_DEG = 24.0    # device reaches this eccentricity (tan24 ~= 0.45)
ECC_MAX_DEG = 27.0            # keep a small margin past the shown field
CORTEX_X_MM = (0.0, 58.5)     # foveal (0 mm) out to ~26 deg (58.5 mm)
DENSITY_SCALE = 1.15          # vs the original foveal grid, to keep the fovea dense
# ----------------------------------------------------------------------------

HERE = os.path.dirname(os.path.abspath(__file__))
REF = os.path.join(HERE, "grid_coords_dipole_valid.yaml")   # original foveal grid
OUT = os.path.join(HERE, "grid_coords_full_field.yaml")


def main():
    params = load_params(os.path.join(HERE, "params.yaml"))
    cortex_model = params["cortex_model"]
    c2vf = get_mapping_from_cortex_to_visual_field(cortex_model)

    # Match (and slightly exceed) the original grid's cortex density + angular span.
    ox, oy = load_coordinates_from_yaml(REF)
    ox, oy = np.asarray(ox), np.asarray(oy)
    y_lo, y_hi = float(oy.min()), float(oy.max())
    density = DENSITY_SCALE * ox.size / ((ox.max() - ox.min()) * (oy.max() - oy.min()))

    rng = np.random.default_rng(SEED)
    n = int(round(density * (CORTEX_X_MM[1] - CORTEX_X_MM[0]) * (y_hi - y_lo)))
    x = rng.uniform(*CORTEX_X_MM, n)
    y = rng.uniform(y_lo, y_hi, n)
    r, phi = complex_to_polar(c2vf(cartesian_to_complex(x, y)))
    r, phi = np.asarray(r), np.asarray(phi)
    keep = np.isfinite(r) & (r <= ECC_MAX_DEG) & (np.abs(phi) < np.pi / 2)
    x, y = x[keep], y[keep]

    with open(OUT, "w") as f:
        f.write("x:\n"); [f.write(f"- {float(v)}\n") for v in x]
        f.write("y:\n"); [f.write(f"- {float(v)}\n") for v in y]

    rf, _ = get_visual_field_coordinates_from_cortex_full(cortex_model, Map(x, y)).polar
    rf = np.asarray(rf)
    print(f"wrote {OUT}")
    print(f"  {x.size} electrodes -> {rf.size} phosphenes, ecc {rf.min():.1f}..{rf.max():.1f} deg")
    print(f"  central 0-8 deg: {(rf < 8).sum()}   ring 8-24 deg: {((rf >= 8) & (rf < 24)).sum()}")


if __name__ == "__main__":
    main()
